services:

  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: go-dev
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8080:8080"
    command: ["air"]
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - DATABASE_URL=postgresql://postgres:password@db:5431/postgres?sslmode=disable

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

volumes:
  go-mod-cache:
